### PR TITLE
docs: Add some more info on its and where the tool itself gets data

### PR DESCRIPTION
**Pull request by lewiscowper**
It looks like the below picture, which makes me thing some styling would need to be done before merging. (line-height or font-size or something CSS related, I'm not 100% sure).

screen shot 2015-12-02 at 17 10 56

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
yar this is useful. i want a section for defining what the LTS rules are in simple terms as well. i was thinking a little about link to a separate page. thoughts, @lewiscowper ?

**Comment by lewiscowper** [comment]
It'd be quite nice to have it in the page if possible, but that relies on the rules being easy to explain in simple terms. (idk because I've only found the complex version).

It'd be quite nice to have them in a box off to one side, with maybe the extended description (everything I've added here + this box), being added with a wrapping "More info on LTS and node" box or similar.

Without much of a design eye, (although I have a bit), we could add a link to a separate page/some simple rules near this PR's section, and then consult someone with more of a design eye about a longer term solution.

How does that sound @ashleygwilliams?

**Comment by ashleygwilliams** [comment]
ooh, you've given me some ideas. we can merge your thing an then maybe i'll do a little redesign stuff. will have to wait til tonight tho

**Comment by lewiscowper** [comment]
No problem. I may be around later on, ping me somewhere if you want someone to bounce ideas off. :+1:

**Pull request closed without merging**
